language: node_js
dist: trusty
cache: yarn

node_js:
    - '7'

before_install:
    - 'curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.0'

before_script:
    - 'npm run clean && npm run lint && npm run build'

after_success:
    - 'npm run coverage'
