language: node_js
dist: trusty
cache: yarn
sudo: required

node_js:
    - '7'

before_install:
    - 'curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.0'

before_script:
    - 'yarn run clean && yarn run lint && yarn run build'

after_success:
    - 'yarn run coverage'
